{% set version = "0.16-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-psychotree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/psychotree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/psychotree/psychotree_{{ version }}.tar.gz
  sha256: ebdbf6fb398a480f4f683e2cb757dd46bb3546660ac6339ea9a635a67766706c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-formula
    - r-partykit >=0.8_4
    - r-psychotools >=0.4_0
  run:
    - r-base
    - r-formula
    - r-partykit >=0.8_4
    - r-psychotools >=0.4_0

test:
  commands:
    - $R -e "library('psychotree')"           # [not win]
    - "\"%R%\" -e \"library('psychotree')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=psychotree
  license: GPL-2.0-or-later
  summary: Recursive partitioning based on psychometric models, employing the general MOB algorithm (from package partykit) to obtain Bradley-Terry trees, Rasch trees, rating scale and partial credit trees, and MPT trees.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
